[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "m2bi-debruijn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest --cov=debruijn -v"
[dependencies]
python = ">=3.13.0,<4"

[pypi-dependencies]
pytest = ">=8.3.3, <9"
pytest-cov = ">=5.0.0, <6"
networkx = ">=3.4.1, <4"
matplotlib = ">=3.9.2, <4"
